language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_0.gemfile
before_script:
  - bundle exec rake turntable:db:reset
script: bundle exec rake spec
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4_0.gemfile
